### ISSUE TITLE
People: Write full research interests

### ISSUE THREAD

**Issue by dmzuckerman** [drylabyrinth/drylabyrinth.github.io#18]
@laderast don't we want the interests listed for people spelled out in full, rather than giving the abbreviations (e.g., "Molecular Dynamics" instead of "md")?  Or did I do something wrong in my profile?  Or would you suggest I lengthen the abbreviations?  Since this is an outward-facing site, I don't think we want to use insider abbreviations.  Maybe I misunderstood how things work.

**Comment by laderast** [comment]
Yes, this can be done. I just haven't found a good way to use the liquid arrays to look up values.

**Comment by dmzuckerman** [comment]
ok.  in the mean time, i'll change the abbreviations to be human-readable

**Comment by laderast** [comment]
This is updated in the current version.
