### ISSUE TITLE
issue with display of people/pictures

### ISSUE THREAD

**Issue by nicolevasilevsky** [drylabyrinth/drylabyrinth.github.io#6]
https://drylabyrinth.netlify.com/people/

I'm using Chrome and the display of the people page is wonky

![image](https://user-images.githubusercontent.com/6722114/52248510-b00e0580-28a3-11e9-981d-4c1c856001bb.png)

**Comment by laderast** [comment]
Yes, I’m trying to fix that - it has to do with the JavaScript and I’m not enough of an expert to figure it out yet. If you reload it, it should look ok

**Comment by lakarstens** [comment]
It still looks wonky (I'm also using Chrome)

**Comment by laderast** [comment]
There is a solution using a jQuery plugin, but I've tried installing it and I'm still having issues fixing it. I think it has to do with the fact that I'm using the theme as a remote theme. Still working on it.

**Comment by laderast** [comment]
This is now fixed.
